#!/usr/bin/env bash
set _BUILDNAME=CustomOS
set _BUILDDIR=bin
set _OVMFDIR=../OVMFbin

qemu-system-x86_64 -serial stdio -drive file=./bin/CustomOS.img -m 512M -cpu qemu64 -drive if=pflash,format=raw,unit=0,file="../OVMFbin/OVMF_CODE-pure-efi.fd",readonly=on -drive if=pflash,format=raw,unit=1,file="../OVMFbin/OVMF_VARS-pure-efi.fd" -net none
